# Generated by Django 6.0.7 on 2026-10-03 11:20

import accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_user_agent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Estate Hub', max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agencies/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.AgentManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='agent_title',
            field=models.CharField(blank=True, default='Administrative Staff', help_text='Designation/Role title (e.g. Administrative Staff, Senior Real Estate Agent)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_featured_agent',
            field=models.BooleanField(default=False, help_text="Feature this agent in the 'Meet Our Agents' section on homepage"),
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='accounts.agency'),
        ),
    ]
