# Generated by Django 6.0.7 on 2026-10-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor_plan_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
