# Generated by Django 6.0.7 on 2026-07-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='show_developer_mansib',
            field=models.BooleanField(default=True, help_text='Show Mansib in footer'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_developer_stradigtech',
            field=models.BooleanField(default=True, help_text='Show Stradigtech in footer'),
        ),
    ]
