# Generated by Django 6.0.7 on 2026-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_sitesetting_show_developer_mansib_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique identifier for the page (e.g., 'about-us', 'privacy-policy')", max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Main content of the page')),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
            },
        ),
    ]
