# Generated by Django 6.0.7 on 2026-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_pagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='ceo_name',
            field=models.CharField(default='Luke Alexander', help_text='Name of the CEO/Founder', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ceo_role',
            field=models.CharField(default='CEO/Founder', help_text='Role title (e.g., CEO/Founder)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ceo_signature',
            field=models.ImageField(blank=True, help_text='Signature image', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Contact Address', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact Email Address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_opentime',
            field=models.TextField(blank=True, help_text='Office Open Hours', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact Phone Number', max_length=50, null=True),
        ),
    ]
