# Generated by Django 6.0.7 on 2026-07-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_sitesetting_ceo_name_sitesetting_ceo_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
