# Generated by Django 6.0.7 on 2026-07-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_sitesetting_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('category', models.CharField(default='Real Estate', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('excerpt', models.TextField(help_text='Short description for the blog list')),
                ('content', models.TextField(help_text='Full blog post content')),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='description',
            field=models.TextField(blank=True, help_text='Content or summary for the page'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='slug',
            field=models.SlugField(help_text="Unique identifier for the page (e.g., 'about-us')", unique=True),
        ),
    ]
