# Generated by Django 6.0.7 on 2026-10-03 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_blogpost_pagecontent_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_description',
            field=models.TextField(blank=True, default='Search thousands of homes for sale and rent. Connect with trusted agents.', help_text='Subtitle or description below the hero title'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_slider_autoplay',
            field=models.BooleanField(default=True, help_text='Enable automatic sliding of background images'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_slider_interval',
            field=models.PositiveIntegerField(default=5000, help_text='Slide transition delay in milliseconds (e.g. 5000 = 5 seconds)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(blank=True, default='Find Your Perfect Home', help_text='Main heading in the homepage hero section', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Single fallback hero image (used if no slides are active)', null=True, upload_to='site/'),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload background image for slider', null=True, upload_to='hero_slides/')),
                ('image_url', models.CharField(blank=True, help_text='Or external image URL (e.g. Unsplash URL)', max_length=1000, null=True)),
                ('title', models.CharField(blank=True, help_text='Optional custom title for this slide (defaults to main hero title if blank)', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional custom description for this slide (defaults to main hero description if blank)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Check to show this slide on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_setting', models.ForeignKey(blank=True, help_text='Associated site settings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='cms.sitesetting')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides (Background Slider)',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
