# Generated by Django 6.0.7 on 2026-10-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_sitesetting_hero_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph (OG) image for social media link sharing (Recommended 1200x630px)', null=True, upload_to='site/'),
        ),
    ]
